//
//  SelectedRepository.swift
//  ToDoApp
//
//  Created by Cagri Terzi on 11/12/2024.
//

import Foundation


/**
 Types of data source.

 Defines data source from which ViewModel processes data.
 
 - Author: Cagri Terzi
 - Important: Add new case when new data source added.
 
 - Attention: ...
 - Author: ...
 - Authors: ...
 - Bug: ...
 - Complexity: ...
 - Copyright: ...
 - Date: ...
 - Experiment: ...
 - Important: ...
 - Invariant: ...
 - Note: ...
 - Postcondition: ...
 - Precondition: ...
 - Remark: ...
 - Remarks: ...
 - Requires: ...
 - See: ...
 - Since: ...
 - Todo: ...
 - Version: ...
 - Warning: ...
 */
enum RepositoryType {
    case inMemoryRepository
    case mockNetworkRepository
    case coreDataRepository
}
